services:
  jenkins-docker:
    image: docker:dind
    ports:
      - 2376:2376
    privileged: true
    restart: on-failure
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker
    command: --storage-driver=overlay2
  jenkins-custom:
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    restart: on-failure
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
  sonarqube:
    image: sonarqube:lts-community
    ports:
      - 9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      jenkins:
        aliases:
          - sonarqube

volumes:
  jenkins-docker-certs:
    external: true
  jenkins-data:
    external: true
  sonarqube_data:
    external: true
  sonarqube_extensions:
    external: true
  sonarqube_logs:
    external: true

networks:
  jenkins:
    external: true
